const test = {
  tag: 0,
  containerInfo: {
    __reactContainer$3hlsah2b4gu: {
      tag: 3,
      key: null,
      elementType: null,
      type: null,
      return: null,
      child: null,
      sibling: null,
      index: 0,
      ref: null,
      pendingProps: null,
      memoizedProps: null,
      updateQueue: {
        baseState: null,
        firstBaseUpdate: {
          eventTime: 300.29499999363907,
          lane: 1,
          tag: 0,
          payload: {
            element: {
              key: null,
              ref: null,
              props: {
                children: [
                  {
                    type: 'div',
                    key: null,
                    ref: null,
                    props: {
                      className: 'game',
                      children: [
                        {
                          type: 'h1',
                          key: null,
                          ref: null,
                          props: {
                            children: [
                              'x',
                              {
                                type: 'span',
                                key: null,
                                ref: null,
                                props: { children: 'o' },
                                _owner: null,
                                _store: {},
                              },
                              'x',
                              {
                                type: 'span',
                                key: null,
                                ref: null,
                                props: { children: 'o' },
                                _owner: null,
                                _store: {},
                              },
                            ],
                          },
                          _owner: null,
                          _store: {},
                        },
                        {
                          key: null,
                          ref: null,
                          props: {},
                          _owner: null,
                          _store: {},
                        },
                        {
                          type: 'div',
                          key: null,
                          ref: null,
                          props: {
                            className: 'board',
                            children: {
                              key: null,
                              ref: null,
                              props: {},
                              _owner: null,
                              _store: {},
                            },
                          },
                          _owner: null,
                          _store: {},
                        },
                      ],
                    },
                    _owner: null,
                    _store: {},
                  },
                  { key: null, ref: null, props: {}, _owner: null, _store: {} },
                ],
              },
              _owner: null,
              _store: {},
            },
          },
          callback: null,
          next: null,
        },
        shared: { pending: null },
        effects: null,
      },
      memoizedState: null,
      dependencies: null,
      mode: 8,
      flags: 0,
      nextEffect: null,
      firstEffect: null,
      lastEffect: null,
      lanes: 1,
      childLanes: 0,
      alternate: {
        tag: 3,
        key: null,
        elementType: null,
        type: null,
        return: null,
        child: {
          tag: 0,
          key: null,
          stateNode: null,
          child: {
            tag: 0,
            key: null,
            stateNode: null,
            child: {
              tag: 10,
              key: null,
              elementType: {
                _context: {
                  _calculateChangedBits: null,
                  _currentValue: {},
                  _threadCount: 0,
                  _currentRenderer: {},
                  _currentRenderer2: null,
                },
              },
              stateNode: null,
              child: {
                tag: 0,
                key: null,
                stateNode: null,
                child: {
                  tag: 5,
                  key: null,
                  elementType: 'div',
                  type: 'div',
                  stateNode: {},
                  child: {
                    tag: 5,
                    key: null,
                    elementType: 'h1',
                    type: 'h1',
                    stateNode: {},
                    child: {
                      tag: 6,
                      key: null,
                      elementType: null,
                      type: null,
                      stateNode: {},
                      child: null,
                      sibling: {
                        tag: 5,
                        key: null,
                        elementType: 'span',
                        type: 'span',
                        stateNode: {},
                        child: null,
                        sibling: {
                          tag: 6,
                          key: null,
                          elementType: null,
                          type: null,
                          stateNode: {},
                          child: null,
                          sibling: {
                            tag: 5,
                            key: null,
                            elementType: 'span',
                            type: 'span',
                            stateNode: {},
                            child: null,
                            sibling: null,
                            index: 3,
                            ref: null,
                            updateQueue: null,
                            memoizedState: null,
                            dependencies: null,
                            mode: 8,
                            flags: 0,
                            nextEffect: null,
                            firstEffect: null,
                            lastEffect: null,
                            lanes: 0,
                            childLanes: 0,
                            alternate: null,
                            actualDuration: 0.07999999797903001,
                            actualStartTime: 307.65999999130145,
                            selfBaseDuration: 0.020000006770715117,
                            treeBaseDuration: 0.020000006770715117,
                            _debugID: 22,
                            _debugSource: {
                              fileName:
                                'C:\\Users\\logan\\Documents\\Development\\toy-apps\\jotai-tic-tac-toe\\src\\index.js',
                              lineNumber: 127,
                              columnNumber: 25,
                            },
                            _debugOwner: null,
                            _debugNeedsRemount: false,
                            _debugHookTypes: null,
                          },
                          index: 2,
                          ref: null,
                          pendingProps: 'x',
                          memoizedProps: 'x',
                          updateQueue: null,
                          memoizedState: null,
                          dependencies: null,
                          mode: 8,
                          flags: 0,
                          nextEffect: null,
                          firstEffect: null,
                          lastEffect: null,
                          lanes: 0,
                          childLanes: 0,
                          alternate: null,
                          actualDuration: 0.020000006770715117,
                          actualStartTime: 307.63999998453073,
                          selfBaseDuration: 0.00999998883344233,
                          treeBaseDuration: 0.00999998883344233,
                          _debugID: 21,
                          _debugSource: null,
                          _debugOwner: null,
                          _debugNeedsRemount: false,
                          _debugHookTypes: null,
                        },
                        index: 1,
                        ref: null,
                        updateQueue: null,
                        memoizedState: null,
                        dependencies: null,
                        mode: 8,
                        flags: 0,
                        nextEffect: null,
                        firstEffect: null,
                        lastEffect: null,
                        lanes: 0,
                        childLanes: 0,
                        alternate: null,
                        actualDuration: 0.939999968977645,
                        actualStartTime: 306.6899999976158,
                        selfBaseDuration: 0.03999998443759978,
                        treeBaseDuration: 0.03999998443759978,
                        _debugID: 20,
                        _debugSource: {
                          fileName:
                            'C:\\Users\\logan\\Documents\\Development\\toy-apps\\jotai-tic-tac-toe\\src\\index.js',
                          lineNumber: 127,
                          columnNumber: 10,
                        },
                        _debugOwner: null,
                        _debugNeedsRemount: false,
                        _debugHookTypes: null,
                      },
                      index: 0,
                      ref: null,
                      pendingProps: 'x',
                      memoizedProps: 'x',
                      updateQueue: null,
                      memoizedState: null,
                      dependencies: null,
                      mode: 8,
                      flags: 0,
                      nextEffect: null,
                      firstEffect: null,
                      lastEffect: null,
                      lanes: 0,
                      childLanes: 0,
                      alternate: null,
                      actualDuration: 0.6350000039674342,
                      actualStartTime: 305.8949999976903,
                      selfBaseDuration: 0.00999998883344233,
                      treeBaseDuration: 0.00999998883344233,
                      _debugID: 19,
                      _debugSource: null,
                      _debugOwner: null,
                      _debugNeedsRemount: false,
                      _debugHookTypes: null,
                    },
                    sibling: {
                      tag: 0,
                      key: null,
                      stateNode: null,
                      child: {
                        tag: 5,
                        key: null,
                        elementType: 'div',
                        type: 'div',
                        stateNode: {
                          __reactProps$3hlsah2b4gu: {
                            className: 'status',
                            children: [
                              {
                                type: 'div',
                                key: null,
                                ref: null,
                                props: {
                                  className: 'message',
                                  children: 'Next player: X',
                                },
                                _store: {},
                              },
                              {
                                type: 'button',
                                key: null,
                                ref: null,
                                props: { children: 'Reset' },
                                _store: {},
                              },
                            ],
                          },
                        },
                        child: {
                          tag: 5,
                          key: null,
                          elementType: 'div',
                          type: 'div',
                          stateNode: {},
                          child: null,
                          sibling: {
                            tag: 5,
                            key: null,
                            elementType: 'button',
                            type: 'button',
                            stateNode: {},
                            child: null,
                            sibling: null,
                            index: 1,
                            ref: null,
                            updateQueue: null,
                            memoizedState: null,
                            dependencies: null,
                            mode: 8,
                            flags: 0,
                            nextEffect: null,
                            firstEffect: null,
                            lastEffect: null,
                            lanes: 0,
                            childLanes: 0,
                            alternate: null,
                            actualDuration: 0.16500000492669642,
                            actualStartTime: 309.80999997700565,
                            selfBaseDuration: 0.029999995604157448,
                            treeBaseDuration: 0.029999995604157448,
                            _debugID: 31,
                            _debugSource: {
                              fileName:
                                'C:\\Users\\logan\\Documents\\Development\\toy-apps\\jotai-tic-tac-toe\\src\\index.js',
                              lineNumber: 102,
                              columnNumber: 7,
                            },
                            _debugNeedsRemount: false,
                            _debugHookTypes: null,
                          },
                          index: 0,
                          ref: null,
                          updateQueue: null,
                          memoizedState: null,
                          dependencies: null,
                          mode: 8,
                          flags: 0,
                          nextEffect: null,
                          firstEffect: null,
                          lastEffect: null,
                          lanes: 0,
                          childLanes: 0,
                          alternate: null,
                          actualDuration: 0.30499999411404133,
                          actualStartTime: 309.49499999405816,
                          selfBaseDuration: 0.004999979864805937,
                          treeBaseDuration: 0.004999979864805937,
                          _debugID: 30,
                          _debugSource: {
                            fileName:
                              'C:\\Users\\logan\\Documents\\Development\\toy-apps\\jotai-tic-tac-toe\\src\\index.js',
                            lineNumber: 101,
                            columnNumber: 7,
                          },
                          _debugNeedsRemount: false,
                          _debugHookTypes: null,
                        },
                        sibling: null,
                        index: 0,
                        ref: null,
                        updateQueue: null,
                        memoizedState: null,
                        dependencies: null,
                        mode: 8,
                        flags: 0,
                        nextEffect: null,
                        firstEffect: null,
                        lastEffect: null,
                        lanes: 0,
                        childLanes: 0,
                        alternate: null,
                        actualDuration: 0.5549999768845737,
                        actualStartTime: 309.45999998948537,
                        selfBaseDuration: 0.029999995604157448,
                        treeBaseDuration: 0.06499997107312083,
                        _debugID: 28,
                        _debugSource: {
                          fileName:
                            'C:\\Users\\logan\\Documents\\Development\\toy-apps\\jotai-tic-tac-toe\\src\\index.js',
                          lineNumber: 100,
                          columnNumber: 5,
                        },
                        _debugNeedsRemount: false,
                        _debugHookTypes: null,
                      },
                      sibling: {
                        tag: 5,
                        key: null,
                        elementType: 'div',
                        type: 'div',
                        stateNode: {},
                        child: {
                          tag: 0,
                          key: null,
                          stateNode: null,
                          child: {
                            tag: 5,
                            key: '0',
                            elementType: 'button',
                            type: 'button',
                            stateNode: {
                              __reactProps$3hlsah2b4gu: {
                                className: 'square null',
                                children: null,
                              },
                            },
                            child: null,
                            sibling: {
                              tag: 5,
                              key: '1',
                              elementType: 'button',
                              type: 'button',
                              stateNode: {
                                __reactProps$3hlsah2b4gu: {
                                  className: 'square null',
                                  children: null,
                                },
                              },
                              child: null,
                              sibling: {
                                tag: 5,
                                key: '2',
                                elementType: 'button',
                                type: 'button',
                                stateNode: {
                                  __reactProps$3hlsah2b4gu: {
                                    className: 'square null',
                                    children: null,
                                  },
                                },
                                child: null,
                                sibling: {
                                  tag: 5,
                                  key: '3',
                                  elementType: 'button',
                                  type: 'button',
                                  stateNode: {
                                    __reactProps$3hlsah2b4gu: {
                                      className: 'square null',
                                      children: null,
                                    },
                                  },
                                  child: null,
                                  sibling: {
                                    tag: 5,
                                    key: '4',
                                    elementType: 'button',
                                    type: 'button',
                                    stateNode: {
                                      __reactProps$3hlsah2b4gu: {
                                        className: 'square null',
                                        children: null,
                                      },
                                    },
                                    child: null,
                                    sibling: {
                                      tag: 5,
                                      key: '5',
                                      elementType: 'button',
                                      type: 'button',
                                      stateNode: {
                                        __reactProps$3hlsah2b4gu: {
                                          className: 'square null',
                                          children: null,
                                        },
                                      },
                                      child: null,
                                      sibling: {
                                        tag: 5,
                                        key: '6',
                                        elementType: 'button',
                                        type: 'button',
                                        stateNode: {
                                          __reactProps$3hlsah2b4gu: {
                                            className: 'square null',
                                            children: null,
                                          },
                                        },
                                        child: null,
                                        sibling: {
                                          tag: 5,
                                          key: '7',
                                          elementType: 'button',
                                          type: 'button',
                                          stateNode: {
                                            __reactProps$3hlsah2b4gu: {
                                              className: 'square null',
                                              children: null,
                                            },
                                          },
                                          child: null,
                                          sibling: {
                                            tag: 5,
                                            key: '8',
                                            elementType: 'button',
                                            type: 'button',
                                            stateNode: {
                                              __reactProps$3hlsah2b4gu: {
                                                className: 'square null',
                                                children: null,
                                              },
                                            },
                                            child: null,
                                            sibling: null,
                                            index: 8,
                                            ref: null,
                                            updateQueue: null,
                                            memoizedState: null,
                                            dependencies: null,
                                            mode: 8,
                                            flags: 0,
                                            nextEffect: null,
                                            firstEffect: null,
                                            lastEffect: null,
                                            lanes: 0,
                                            childLanes: 0,
                                            alternate: null,
                                            actualDuration: 0.034999975468963385,
                                            actualStartTime: 311.4449999993667,
                                            selfBaseDuration: 0.004999979864805937,
                                            treeBaseDuration: 0.004999979864805937,
                                            _debugID: 45,
                                            _debugSource: {
                                              fileName:
                                                'C:\\Users\\logan\\Documents\\Development\\toy-apps\\jotai-tic-tac-toe\\src\\index.js',
                                              lineNumber: 84,
                                              columnNumber: 9,
                                            },
                                            _debugNeedsRemount: false,
                                            _debugHookTypes: null,
                                          },
                                          index: 7,
                                          ref: null,
                                          updateQueue: null,
                                          memoizedState: null,
                                          dependencies: null,
                                          mode: 8,
                                          flags: 0,
                                          nextEffect: null,
                                          firstEffect: null,
                                          lastEffect: null,
                                          lanes: 0,
                                          childLanes: 0,
                                          alternate: null,
                                          actualDuration: 0.03999998443759978,
                                          actualStartTime: 311.3949999969918,
                                          selfBaseDuration: 0.00999998883344233,
                                          treeBaseDuration: 0.00999998883344233,
                                          _debugID: 44,
                                          _debugSource: {
                                            fileName:
                                              'C:\\Users\\logan\\Documents\\Development\\toy-apps\\jotai-tic-tac-toe\\src\\index.js',
                                            lineNumber: 84,
                                            columnNumber: 9,
                                          },
                                          _debugNeedsRemount: false,
                                          _debugHookTypes: null,
                                        },
                                        index: 6,
                                        ref: null,
                                        updateQueue: null,
                                        memoizedState: null,
                                        dependencies: null,
                                        mode: 8,
                                        flags: 0,
                                        nextEffect: null,
                                        firstEffect: null,
                                        lastEffect: null,
                                        lanes: 0,
                                        childLanes: 0,
                                        alternate: null,
                                        actualDuration: 0.050000002374872565,
                                        actualStartTime: 311.34499999461696,
                                        selfBaseDuration: 0.014999997802078724,
                                        treeBaseDuration: 0.014999997802078724,
                                        _debugID: 43,
                                        _debugSource: {
                                          fileName:
                                            'C:\\Users\\logan\\Documents\\Development\\toy-apps\\jotai-tic-tac-toe\\src\\index.js',
                                          lineNumber: 84,
                                          columnNumber: 9,
                                        },
                                        _debugNeedsRemount: false,
                                        _debugHookTypes: null,
                                      },
                                      index: 5,
                                      ref: null,
                                      updateQueue: null,
                                      memoizedState: null,
                                      dependencies: null,
                                      mode: 8,
                                      flags: 0,
                                      nextEffect: null,
                                      firstEffect: null,
                                      lastEffect: null,
                                      lanes: 0,
                                      childLanes: 0,
                                      alternate: null,
                                      actualDuration: 0.03999998443759978,
                                      actualStartTime: 311.3000000012107,
                                      selfBaseDuration: 0.00999998883344233,
                                      treeBaseDuration: 0.00999998883344233,
                                      _debugID: 42,
                                      _debugSource: {
                                        fileName:
                                          'C:\\Users\\logan\\Documents\\Development\\toy-apps\\jotai-tic-tac-toe\\src\\index.js',
                                        lineNumber: 84,
                                        columnNumber: 9,
                                      },
                                      _debugNeedsRemount: false,
                                      _debugHookTypes: null,
                                    },
                                    index: 4,
                                    ref: null,
                                    updateQueue: null,
                                    memoizedState: null,
                                    dependencies: null,
                                    mode: 8,
                                    flags: 0,
                                    nextEffect: null,
                                    firstEffect: null,
                                    lastEffect: null,
                                    lanes: 0,
                                    childLanes: 0,
                                    alternate: null,
                                    actualDuration: 0.04500002251006663,
                                    actualStartTime: 311.25499997870065,
                                    selfBaseDuration: 0.010000017937272787,
                                    treeBaseDuration: 0.010000017937272787,
                                    _debugID: 41,
                                    _debugSource: {
                                      fileName:
                                        'C:\\Users\\logan\\Documents\\Development\\toy-apps\\jotai-tic-tac-toe\\src\\index.js',
                                      lineNumber: 84,
                                      columnNumber: 9,
                                    },
                                    _debugNeedsRemount: false,
                                    _debugHookTypes: null,
                                  },
                                  index: 3,
                                  ref: null,
                                  updateQueue: null,
                                  memoizedState: null,
                                  dependencies: null,
                                  mode: 8,
                                  flags: 0,
                                  nextEffect: null,
                                  firstEffect: null,
                                  lastEffect: null,
                                  lanes: 0,
                                  childLanes: 0,
                                  alternate: null,
                                  actualDuration: 0.06500000017695129,
                                  actualStartTime: 311.1899999785237,
                                  selfBaseDuration: 0.014999997802078724,
                                  treeBaseDuration: 0.014999997802078724,
                                  _debugID: 40,
                                  _debugSource: {
                                    fileName:
                                      'C:\\Users\\logan\\Documents\\Development\\toy-apps\\jotai-tic-tac-toe\\src\\index.js',
                                    lineNumber: 84,
                                    columnNumber: 9,
                                  },
                                  _debugNeedsRemount: false,
                                  _debugHookTypes: null,
                                },
                                index: 2,
                                ref: null,
                                updateQueue: null,
                                memoizedState: null,
                                dependencies: null,
                                mode: 8,
                                flags: 0,
                                nextEffect: null,
                                firstEffect: null,
                                lastEffect: null,
                                lanes: 0,
                                childLanes: 0,
                                alternate: null,
                                actualDuration: 0.0549999822396785,
                                actualStartTime: 311.134999996284,
                                selfBaseDuration: 0.014999997802078724,
                                treeBaseDuration: 0.014999997802078724,
                                _debugID: 39,
                                _debugSource: {
                                  fileName:
                                    'C:\\Users\\logan\\Documents\\Development\\toy-apps\\jotai-tic-tac-toe\\src\\index.js',
                                  lineNumber: 84,
                                  columnNumber: 9,
                                },
                                _debugNeedsRemount: false,
                                _debugHookTypes: null,
                              },
                              index: 1,
                              ref: null,
                              updateQueue: null,
                              memoizedState: null,
                              dependencies: null,
                              mode: 8,
                              flags: 0,
                              nextEffect: null,
                              firstEffect: null,
                              lastEffect: null,
                              lanes: 0,
                              childLanes: 0,
                              alternate: null,
                              actualDuration: 0.07500001811422408,
                              actualStartTime: 311.0599999781698,
                              selfBaseDuration: 0.010000017937272787,
                              treeBaseDuration: 0.010000017937272787,
                              _debugID: 38,
                              _debugSource: {
                                fileName:
                                  'C:\\Users\\logan\\Documents\\Development\\toy-apps\\jotai-tic-tac-toe\\src\\index.js',
                                lineNumber: 84,
                                columnNumber: 9,
                              },
                              _debugNeedsRemount: false,
                              _debugHookTypes: null,
                            },
                            index: 0,
                            ref: null,
                            updateQueue: null,
                            memoizedState: null,
                            dependencies: null,
                            mode: 8,
                            flags: 0,
                            nextEffect: null,
                            firstEffect: null,
                            lastEffect: null,
                            lanes: 0,
                            childLanes: 0,
                            alternate: null,
                            actualDuration: 0.13000002945773304,
                            actualStartTime: 310.9149999800138,
                            selfBaseDuration: 0.02500001573935151,
                            treeBaseDuration: 0.02500001573935151,
                            _debugID: 37,
                            _debugSource: {
                              fileName:
                                'C:\\Users\\logan\\Documents\\Development\\toy-apps\\jotai-tic-tac-toe\\src\\index.js',
                              lineNumber: 84,
                              columnNumber: 9,
                            },
                            _debugNeedsRemount: false,
                            _debugHookTypes: null,
                          },
                          sibling: null,
                          index: 0,
                          ref: null,
                          updateQueue: {
                            lastEffect: {
                              tag: 5,
                              deps: [null, { debugLabel: 'winnerAtom' }],
                              next: {
                                tag: 3,
                                deps: [{}],
                                next: {
                                  tag: 3,
                                  deps: [null],
                                  next: {
                                    tag: 5,
                                    deps: [
                                      null,
                                      {
                                        init: null,
                                        debugLabel: 'resetSquaresAtom',
                                      },
                                    ],
                                    next: {
                                      tag: 3,
                                      deps: [null],
                                      next: {
                                        tag: 3,
                                        deps: [null],
                                        next: {
                                          tag: 5,
                                          deps: [
                                            null,
                                            { debugLabel: 'selectSquareAtom' },
                                          ],
                                          next: {
                                            tag: 3,
                                            deps: [null],
                                            next: { tag: 3, deps: [null] },
                                          },
                                        },
                                      },
                                    },
                                  },
                                },
                              },
                            },
                          },
                          memoizedState: {
                            memoizedState: [null, [null]],
                            baseState: null,
                            baseQueue: null,
                            queue: null,
                            next: {
                              memoizedState: [
                                [{ a: {}, m: {}, w: {} }, null],
                                null,
                              ],
                              baseQueue: null,
                              queue: {
                                pending: { lane: 1, action: [1, null] },
                              },
                              next: {
                                baseState: null,
                                baseQueue: null,
                                queue: null,
                                next: {
                                  memoizedState: [null, [null]],
                                  baseState: null,
                                  baseQueue: null,
                                  queue: null,
                                  next: {
                                    memoizedState: [null, null],
                                    baseQueue: null,
                                    queue: {
                                      pending: { lane: 1, action: [1, null] },
                                    },
                                    next: {
                                      baseState: null,
                                      baseQueue: null,
                                      queue: null,
                                      next: {
                                        baseState: null,
                                        baseQueue: null,
                                        queue: null,
                                        next: {
                                          memoizedState: [null, [null, null]],
                                          baseState: null,
                                          baseQueue: null,
                                          queue: null,
                                          next: {
                                            memoizedState: [null, [null]],
                                            baseState: null,
                                            baseQueue: null,
                                            queue: null,
                                            next: {
                                              memoizedState: [null, null],
                                              baseQueue: null,
                                              queue: {
                                                pending: {
                                                  lane: 1,
                                                  action: [1, null],
                                                },
                                              },
                                              next: {
                                                baseState: null,
                                                baseQueue: null,
                                                queue: null,
                                                next: {
                                                  memoizedState: [null, [null]],
                                                  baseState: null,
                                                  baseQueue: null,
                                                  queue: null,
                                                  next: {
                                                    memoizedState: [
                                                      null,
                                                      [
                                                        null,
                                                        null,
                                                        null,
                                                        null,
                                                        null,
                                                        null,
                                                        null,
                                                        null,
                                                        null,
                                                      ],
                                                    ],
                                                    baseQueue: null,
                                                    queue: {
                                                      pending: {
                                                        lane: 1,
                                                        action: [1, null],
                                                      },
                                                    },
                                                    next: {
                                                      baseState: null,
                                                      baseQueue: null,
                                                      queue: null,
                                                      next: {
                                                        baseState: null,
                                                        baseQueue: null,
                                                        queue: null,
                                                        next: {
                                                          memoizedState: [
                                                            null,
                                                            [null, null],
                                                          ],
                                                          baseState: null,
                                                          baseQueue: null,
                                                          queue: null,
                                                          next: {
                                                            memoizedState: [
                                                              null,
                                                              [null],
                                                            ],
                                                            baseState: null,
                                                            baseQueue: null,
                                                            queue: null,
                                                            next: {
                                                              memoizedState: [
                                                                null,
                                                                null,
                                                              ],
                                                              baseQueue: null,
                                                              queue: {
                                                                pending: {
                                                                  lane: 1,
                                                                  action: [
                                                                    1,
                                                                    null,
                                                                  ],
                                                                },
                                                              },
                                                              next: {
                                                                baseState: null,
                                                                baseQueue: null,
                                                                queue: null,
                                                                next: {
                                                                  memoizedState: [
                                                                    null,
                                                                    [null],
                                                                  ],
                                                                  baseState: null,
                                                                  baseQueue: null,
                                                                  queue: null,
                                                                  next: {
                                                                    memoizedState: [
                                                                      null,
                                                                      null,
                                                                    ],
                                                                    baseQueue: null,
                                                                    queue: {
                                                                      pending: {
                                                                        lane: 1,
                                                                        action: [
                                                                          1,
                                                                          null,
                                                                        ],
                                                                      },
                                                                    },
                                                                    next: {
                                                                      baseState: null,
                                                                      baseQueue: null,
                                                                      queue: null,
                                                                      next: {
                                                                        baseState: null,
                                                                        baseQueue: null,
                                                                        queue: null,
                                                                        next: {
                                                                          memoizedState: [
                                                                            null,
                                                                            [
                                                                              null,
                                                                              null,
                                                                            ],
                                                                          ],
                                                                          baseState: null,
                                                                          baseQueue: null,
                                                                          queue: null,
                                                                          next: null,
                                                                        },
                                                                      },
                                                                    },
                                                                  },
                                                                },
                                                              },
                                                            },
                                                          },
                                                        },
                                                      },
                                                    },
                                                  },
                                                },
                                              },
                                            },
                                          },
                                        },
                                      },
                                    },
                                  },
                                },
                              },
                            },
                          },
                          dependencies: {
                            lanes: 0,
                            firstContext: {
                              observedBits: 1073741823,
                              next: null,
                            },
                            responders: null,
                          },
                          mode: 8,
                          flags: 517,
                          nextEffect: null,
                          firstEffect: null,
                          lastEffect: null,
                          lanes: 0,
                          childLanes: 0,
                          alternate: null,
                          actualDuration: 1.3650000328198075,
                          actualStartTime: 310.08499997551553,
                          selfBaseDuration: 0.8250000246334821,
                          treeBaseDuration: 0.940000027185306,
                          _debugID: 35,
                          _debugSource: {
                            fileName:
                              'C:\\Users\\logan\\Documents\\Development\\toy-apps\\jotai-tic-tac-toe\\src\\index.js',
                            lineNumber: 131,
                            columnNumber: 9,
                          },
                          _debugOwner: null,
                          _debugNeedsRemount: false,
                          _debugHookTypes: [
                            'useDebugValue',
                            'useCallback',
                            'useContext',
                            'useReducer',
                            'useLayoutEffect',
                            'useCallback',
                            'useContext',
                            'useReducer',
                            'useLayoutEffect',
                            'useEffect',
                            'useCallback',
                            'useDebugValue',
                            'useDebugValue',
                            'useCallback',
                            'useContext',
                            'useReducer',
                            'useLayoutEffect',
                            'useCallback',
                            'useContext',
                            'useReducer',
                            'useLayoutEffect',
                            'useEffect',
                            'useCallback',
                            'useDebugValue',
                            'useDebugValue',
                            'useCallback',
                            'useContext',
                            'useReducer',
                            'useLayoutEffect',
                            'useCallback',
                            'useContext',
                            'useReducer',
                            'useLayoutEffect',
                            'useEffect',
                            'useCallback',
                            'useDebugValue',
                          ],
                        },
                        sibling: null,
                        index: 2,
                        ref: null,
                        updateQueue: null,
                        memoizedState: null,
                        dependencies: null,
                        mode: 8,
                        flags: 0,
                        nextEffect: null,
                        lanes: 0,
                        childLanes: 0,
                        alternate: null,
                        actualDuration: 1.4400000218302011,
                        actualStartTime: 310.0549999799114,
                        selfBaseDuration: 0.020000006770715117,
                        treeBaseDuration: 0.9600000339560211,
                        _debugID: 17,
                        _debugSource: {
                          fileName:
                            'C:\\Users\\logan\\Documents\\Development\\toy-apps\\jotai-tic-tac-toe\\src\\index.js',
                          lineNumber: 130,
                          columnNumber: 7,
                        },
                        _debugOwner: null,
                        _debugNeedsRemount: false,
                        _debugHookTypes: null,
                      },
                      index: 1,
                      ref: null,
                      updateQueue: {
                        lastEffect: {
                          tag: 5,
                          deps: [null, null],
                          next: {
                            tag: 3,
                            deps: [null],
                            next: {
                              tag: 3,
                              deps: [null],
                              next: {
                                tag: 5,
                                deps: [null, { debugLabel: 'statusAtom' }],
                                next: {
                                  tag: 3,
                                  deps: [null],
                                  next: { tag: 3, deps: [null] },
                                },
                              },
                            },
                          },
                        },
                      },
                      memoizedState: {
                        memoizedState: [null, [null]],
                        baseState: null,
                        baseQueue: null,
                        queue: null,
                        next: {
                          memoizedState: [null, null],
                          baseQueue: null,
                          queue: { pending: { lane: 1, action: [1, null] } },
                          next: {
                            baseState: null,
                            baseQueue: null,
                            queue: null,
                            next: {
                              memoizedState: [null, [null]],
                              baseState: null,
                              baseQueue: null,
                              queue: null,
                              next: {
                                memoizedState: [null, 'Next player: X'],
                                baseQueue: null,
                                queue: {
                                  pending: { lane: 1, action: [1, null] },
                                },
                                next: {
                                  baseState: null,
                                  baseQueue: null,
                                  queue: null,
                                  next: {
                                    baseState: null,
                                    baseQueue: null,
                                    queue: null,
                                    next: {
                                      memoizedState: [null, [null, null]],
                                      baseState: null,
                                      baseQueue: null,
                                      queue: null,
                                      next: {
                                        memoizedState: [null, [null]],
                                        baseState: null,
                                        baseQueue: null,
                                        queue: null,
                                        next: {
                                          memoizedState: [null, null],
                                          baseQueue: null,
                                          queue: {
                                            pending: {
                                              lane: 1,
                                              action: [1, null],
                                            },
                                          },
                                          next: {
                                            baseState: null,
                                            baseQueue: null,
                                            queue: null,
                                            next: {
                                              memoizedState: [null, [null]],
                                              baseState: null,
                                              baseQueue: null,
                                              queue: null,
                                              next: {
                                                memoizedState: [null, null],
                                                baseQueue: null,
                                                queue: {
                                                  pending: {
                                                    lane: 1,
                                                    action: [1, null],
                                                  },
                                                },
                                                next: {
                                                  baseState: null,
                                                  baseQueue: null,
                                                  queue: null,
                                                  next: {
                                                    baseState: null,
                                                    baseQueue: null,
                                                    queue: null,
                                                    next: {
                                                      memoizedState: [
                                                        null,
                                                        [null, null],
                                                      ],
                                                      baseState: null,
                                                      baseQueue: null,
                                                      queue: null,
                                                      next: null,
                                                    },
                                                  },
                                                },
                                              },
                                            },
                                          },
                                        },
                                      },
                                    },
                                  },
                                },
                              },
                            },
                          },
                        },
                      },
                      dependencies: {
                        lanes: 0,
                        firstContext: { observedBits: 1073741823, next: null },
                        responders: null,
                      },
                      mode: 8,
                      flags: 517,
                      nextEffect: null,
                      firstEffect: null,
                      lastEffect: null,
                      lanes: 0,
                      childLanes: 0,
                      alternate: null,
                      actualDuration: 2.1749999723397195,
                      actualStartTime: 307.8399999940302,
                      selfBaseDuration: 1.6199999954551458,
                      treeBaseDuration: 1.6849999665282667,
                      _debugID: 16,
                      _debugSource: {
                        fileName:
                          'C:\\Users\\logan\\Documents\\Development\\toy-apps\\jotai-tic-tac-toe\\src\\index.js',
                        lineNumber: 129,
                        columnNumber: 7,
                      },
                      _debugOwner: null,
                      _debugNeedsRemount: false,
                      _debugHookTypes: [
                        'useDebugValue',
                        'useCallback',
                        'useContext',
                        'useReducer',
                        'useLayoutEffect',
                        'useCallback',
                        'useContext',
                        'useReducer',
                        'useLayoutEffect',
                        'useEffect',
                        'useCallback',
                        'useDebugValue',
                        'useDebugValue',
                        'useCallback',
                        'useContext',
                        'useReducer',
                        'useLayoutEffect',
                        'useCallback',
                        'useContext',
                        'useReducer',
                        'useLayoutEffect',
                        'useEffect',
                        'useCallback',
                        'useDebugValue',
                      ],
                    },
                    index: 0,
                    ref: null,
                    updateQueue: null,
                    memoizedState: null,
                    dependencies: null,
                    mode: 8,
                    flags: 0,
                    nextEffect: null,
                    firstEffect: null,
                    lastEffect: null,
                    lanes: 0,
                    childLanes: 0,
                    alternate: null,
                    actualDuration: 1.7999999690800905,
                    actualStartTime: 305.84499999531545,
                    selfBaseDuration: 0.04499999340623617,
                    treeBaseDuration: 0.12499996228143573,
                    _debugID: 15,
                    _debugSource: {
                      fileName:
                        'C:\\Users\\logan\\Documents\\Development\\toy-apps\\jotai-tic-tac-toe\\src\\index.js',
                      lineNumber: 126,
                      columnNumber: 7,
                    },
                    _debugOwner: null,
                    _debugNeedsRemount: false,
                    _debugHookTypes: null,
                  },
                  sibling: {
                    tag: 0,
                    key: null,
                    stateNode: null,
                    child: null,
                    sibling: null,
                    index: 1,
                    ref: null,
                    updateQueue: {
                      lastEffect: {
                        tag: 5,
                        deps: [null, null],
                        next: {
                          tag: 5,
                          deps: [],
                          next: {
                            tag: 5,
                            deps: [],
                            next: {
                              tag: 3,
                              deps: [null],
                              next: { tag: 3, deps: [null] },
                            },
                          },
                        },
                      },
                    },
                    memoizedState: {
                      memoizedState: { current: 0 },
                      baseState: null,
                      baseQueue: null,
                      queue: null,
                      next: {
                        memoizedState: { width: 530, height: 962 },
                        baseQueue: null,
                        queue: { pending: null },
                        next: {
                          memoizedState: [null, []],
                          baseState: null,
                          baseQueue: null,
                          queue: null,
                          next: {
                            memoizedState: {},
                            baseState: null,
                            baseQueue: null,
                            queue: null,
                            next: {
                              baseState: null,
                              baseQueue: null,
                              queue: null,
                              next: {
                                baseState: null,
                                baseQueue: null,
                                queue: null,
                                next: {
                                  memoizedState: [null, [null]],
                                  baseState: null,
                                  baseQueue: null,
                                  queue: null,
                                  next: {
                                    memoizedState: [null, null],
                                    baseQueue: null,
                                    queue: {
                                      pending: { lane: 1, action: [1, null] },
                                    },
                                    next: {
                                      baseState: null,
                                      baseQueue: null,
                                      queue: null,
                                      next: {
                                        memoizedState: [null, [null]],
                                        baseState: null,
                                        baseQueue: null,
                                        queue: null,
                                        next: {
                                          memoizedState: [null, null],
                                          baseQueue: null,
                                          queue: {
                                            pending: {
                                              lane: 1,
                                              action: [1, null],
                                            },
                                          },
                                          next: {
                                            baseState: null,
                                            baseQueue: null,
                                            queue: null,
                                            next: {
                                              baseState: null,
                                              baseQueue: null,
                                              queue: null,
                                              next: {
                                                memoizedState: [
                                                  null,
                                                  [null, null],
                                                ],
                                                baseState: null,
                                                baseQueue: null,
                                                queue: null,
                                                next: null,
                                              },
                                            },
                                          },
                                        },
                                      },
                                    },
                                  },
                                },
                              },
                            },
                          },
                        },
                      },
                    },
                    dependencies: {
                      lanes: 0,
                      firstContext: { observedBits: 1073741823, next: null },
                      responders: null,
                    },
                    mode: 8,
                    flags: 517,
                    nextEffect: null,
                    firstEffect: null,
                    lastEffect: null,
                    lanes: 0,
                    childLanes: 0,
                    alternate: null,
                    actualDuration: 0.39999998989515007,
                    actualStartTime: 311.5899999975227,
                    selfBaseDuration: 0.39999998989515007,
                    treeBaseDuration: 0.39999998989515007,
                    _debugID: 13,
                    _debugSource: {
                      fileName:
                        'C:\\Users\\logan\\Documents\\Development\\toy-apps\\jotai-tic-tac-toe\\src\\index.js',
                      lineNumber: 134,
                      columnNumber: 5,
                    },
                    _debugOwner: null,
                    _debugNeedsRemount: false,
                    _debugHookTypes: [
                      'useRef',
                      'useState',
                      'useCallback',
                      'useRef',
                      'useEffect',
                      'useEffect',
                      'useDebugValue',
                      'useCallback',
                      'useContext',
                      'useReducer',
                      'useLayoutEffect',
                      'useCallback',
                      'useContext',
                      'useReducer',
                      'useLayoutEffect',
                      'useEffect',
                      'useCallback',
                      'useDebugValue',
                    ],
                  },
                  index: 0,
                  ref: null,
                  updateQueue: null,
                  memoizedState: null,
                  dependencies: null,
                  mode: 8,
                  flags: 0,
                  nextEffect: null,
                  lanes: 0,
                  childLanes: 0,
                  alternate: null,
                  actualDuration: 5.724999966332689,
                  actualStartTime: 305.5649999878369,
                  selfBaseDuration: 0.2800000074785203,
                  treeBaseDuration: 3.0499999702442437,
                  _debugID: 12,
                  _debugSource: {
                    fileName:
                      'C:\\Users\\logan\\Documents\\Development\\toy-apps\\jotai-tic-tac-toe\\src\\index.js',
                    lineNumber: 125,
                    columnNumber: 5,
                  },
                  _debugOwner: null,
                  _debugNeedsRemount: false,
                  _debugHookTypes: null,
                },
                sibling: null,
                index: 0,
                ref: null,
                pendingProps: { r: {} },
                updateQueue: null,
                memoizedState: null,
                dependencies: {
                  lanes: 0,
                  firstContext: { observedBits: 1073741823, next: null },
                  responders: null,
                },
                mode: 8,
                flags: 1,
                nextEffect: null,
                lanes: 0,
                childLanes: 0,
                alternate: null,
                actualDuration: 6.734999973559752,
                actualStartTime: 304.9449999816716,
                selfBaseDuration: 0.6100000173319131,
                treeBaseDuration: 4.059999977471307,
                _debugID: 10,
                _debugSource: null,
                _debugNeedsRemount: false,
                _debugHookTypes: ['useContext'],
              },
              sibling: null,
              index: 0,
              ref: null,
              pendingProps: {
                value: {},
                children: { key: null, ref: null, _store: {} },
              },
              updateQueue: null,
              memoizedState: null,
              dependencies: null,
              mode: 8,
              flags: 0,
              nextEffect: null,
              lanes: 0,
              childLanes: 0,
              alternate: null,
              actualDuration: 6.994999974267557,
              actualStartTime: 304.7149999765679,
              selfBaseDuration: 0.22499999613501132,
              treeBaseDuration: 4.284999973606318,
              _debugID: 8,
              _debugSource: null,
              _debugNeedsRemount: false,
              _debugHookTypes: null,
            },
            sibling: null,
            index: 0,
            ref: null,
            pendingProps: {},
            updateQueue: { lastEffect: { tag: 3, deps: [null] } },
            memoizedState: {
              memoizedState: {},
              baseState: null,
              baseQueue: null,
              queue: null,
              next: {
                memoizedState: { current: 1 },
                baseState: null,
                baseQueue: null,
                queue: null,
                next: {
                  memoizedState: {},
                  baseState: null,
                  baseQueue: null,
                  queue: null,
                  next: {
                    baseState: null,
                    baseQueue: null,
                    queue: null,
                    next: null,
                  },
                },
              },
            },
            dependencies: null,
            mode: 8,
            flags: 5,
            nextEffect: null,
            lanes: 0,
            childLanes: 0,
            alternate: null,
            actualDuration: 7.214999990537763,
            actualStartTime: 304.4899999804329,
            selfBaseDuration: 0.22000001627020538,
            treeBaseDuration: 4.504999989876524,
            _debugID: 6,
            _debugSource: null,
            _debugNeedsRemount: false,
            _debugHookTypes: ['useRef', 'useRef', 'useRef', 'useLayoutEffect'],
          },
          sibling: null,
          index: 0,
          ref: null,
          updateQueue: { lastEffect: { tag: 5, deps: null } },
          memoizedState: {
            baseState: null,
            baseQueue: null,
            queue: null,
            next: {
              baseQueue: null,
              queue: {
                pending: {
                  lane: 1,
                  next: {
                    lane: 1,
                    next: {
                      lane: 1,
                      next: { lane: 1, next: { lane: 1, next: { lane: 1 } } },
                    },
                  },
                },
              },
              next: {
                memoizedState: {},
                baseState: null,
                baseQueue: null,
                queue: null,
                next: {
                  memoizedState: [null, []],
                  baseState: null,
                  baseQueue: null,
                  queue: null,
                  next: {
                    baseState: null,
                    baseQueue: null,
                    queue: null,
                    next: null,
                  },
                },
              },
            },
          },
          dependencies: null,
          mode: 8,
          flags: 517,
          nextEffect: null,
          lanes: 0,
          childLanes: 0,
          alternate: null,
          actualDuration: 8.960000006482005,
          actualStartTime: 302.7349999756552,
          selfBaseDuration: 1.7450000159442425,
          treeBaseDuration: 6.250000005820766,
          _debugID: 4,
          _debugSource: {
            fileName:
              'C:\\Users\\logan\\Documents\\Development\\toy-apps\\jotai-tic-tac-toe\\src\\index.js',
            lineNumber: 124,
            columnNumber: 3,
          },
          _debugOwner: null,
          _debugNeedsRemount: false,
          _debugHookTypes: [
            'useRef',
            'useState',
            'useRef',
            'useMemo',
            'useEffect',
            'useDebugValue',
          ],
        },
        sibling: null,
        index: 0,
        ref: null,
        pendingProps: null,
        memoizedProps: null,
        updateQueue: {
          baseState: {},
          firstBaseUpdate: null,
          lastBaseUpdate: null,
          effects: null,
        },
        dependencies: null,
        mode: 8,
        flags: 256,
        nextEffect: null,
        lanes: 0,
        childLanes: 0,
        actualDuration: 10.405000008177012,
        actualStartTime: 301.34999999427237,
        selfBaseDuration: 1.3800000015180558,
        treeBaseDuration: 7.630000007338822,
        _debugID: 1,
        _debugSource: null,
        _debugOwner: null,
        _debugNeedsRemount: false,
        _debugHookTypes: null,
      },
      actualDuration: 0,
      actualStartTime: -1,
      selfBaseDuration: 0,
      treeBaseDuration: 0,
      _debugID: 1,
      _debugSource: null,
      _debugOwner: null,
      _debugNeedsRemount: false,
      _debugHookTypes: null,
    },
    _reactListeninggvvbgc11p3: true,
    __reactEvents$3hlsah2b4gu: {},
    _reactRootContainer: {},
  },
  pendingChildren: null,
  pingCache: null,
  finishedWork: null,
  timeoutHandle: -1,
  context: {},
  pendingContext: null,
  hydrate: false,
  callbackNode: null,
  callbackPriority: 0,
  eventTimes: [
    -1,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
  ],
  expirationTimes: [
    -1,
    -1,
    -1,
    -1,
    -1,
    -1,
    -1,
    -1,
    -1,
    -1,
    -1,
    -1,
    -1,
    -1,
    -1,
    -1,
    -1,
    -1,
    -1,
    -1,
    -1,
    -1,
    -1,
    -1,
    -1,
    -1,
    -1,
    -1,
    -1,
    -1,
    -1,
  ],
  pendingLanes: 0,
  suspendedLanes: 0,
  pingedLanes: 0,
  expiredLanes: 0,
  mutableReadLanes: 0,
  finishedLanes: 0,
  entangledLanes: 0,
  entanglements: [
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
  ],
  mutableSourceEagerHydrationData: null,
  interactionThreadID: 1,
  memoizedInteractions: {},
  pendingInteractionMap: {},
  _debugRootType: 'createLegacyRoot()',
};
